### ISSUE TITLE
meta 대신에 strong을 사용하는 것은 어떨까요?

### ISSUE THREAD

**Issue by July249** [beyondDevelops/Test#2]
meta 대신에 strong을 사용하는 것은 어떨까요?

_Originally posted by @July249 in https://github.com/beyondDevelops/Test/pull/1#discussion_r1035908837_

**Comment by GreattitJY** [comment]
어..?

**Comment by IntHyun** [comment]
ㅋㅋ?

**Comment by July249** [comment]
너무들 하시네요 ㅠㅠ 제가 바보인걸로 케이스 종결 ㅋㅋㅋㅋ
